### ISSUE TITLE
Traditional Object Oriented approach or Component  Entity System?

### ISSUE THREAD

**Issue by izz-j** [IsemanTech/Cyber-Pong#4]
Because I want to add more advanced features and a more modular design I am working on redesigning this entire program. I'm wondering which of the two would be better? Ofcourse the traditional way would make a Entity header file then have the paddles be inherited from the class. But a more data oriented has caught my intrigue and thinking of using this approach. What do you think?

**Comment by lethargilistic** [comment]
I've never used ECS intentionally, myself. Since there are only a few objects in this game, there's not really much of a benefit to one over another. Since you call it "traditional," I assume you've done OOP before, so I say follow what you're interested in and do ECS this time.

**Comment by izz-j** [comment]
Okay. Yeah I'll do more reading on ECS. Yeah I know there are only 3 objects in the game but I actually think it would make it all the easier to test this out.  As you can see, when I first started this project I was just learning how SFML works and wanted to kind of make things as simple as possible and code everything in one file. This is why the code doesn't look too friendly right now. But now I want to add more features such as an Intro scene, a main menu, pause and resume, and so on. So I am looking into totally redesigning the game.

**Comment by lethargilistic** [comment]
All the more reason to lean into the changes and go for it.

**Comment by izz-j** [comment]
Okay I will keep you updated. If its easier for you we can chat through email. My email is on my profile. send me an email if you want so I don't have to open issues to share ideas with you.

**Comment by izz-j** [comment]
oh and also can you change master to release and test to dev in the documentation?

**Comment by lethargilistic** [comment]
I get emails from projects I watch, anyway. It's better to have discussions in a forum attached to the project, so the record is kept better.

**Comment by izz-j** [comment]
Any ideas on what forum we should use?

**Comment by lethargilistic** [comment]
The issue tracker. x)
